jasypt:
    encryptor:
        password: qrhodocqnjnskcknklbmfkbkldcbasdgksnlsncank21hksnk
server:
    context-path: /
    port: 80
    undertow:
      # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
      io-threads: 4
      # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
      worker-threads: 20
      # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
      # 每块buffer的空间大小,越小的空间被利用越充分
      buffer-size: 1024
      # 是否分配的直接内存
      direct-buffers: true
spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        initial-size: 10
        max-active: 20
        max-idle: 8
        min-idle: 8
        password: ENC(IYbXimNmm3VvexjGvjvkFA==)
        url: jdbc:mysql://localhost:3306/web1
        username: root
    http:
        encoding:
            charset: UTF-8
    rabbitmq:
        mqtt:
            password: guest
            serveruri: tcp://127.0.0.1:1883
            topic: bibi
            username: guest