server:
  port: 80
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    initial-size: 10
    max-active: 20
    max-idle: 8
    min-idle: 8
    url: jdbc:mysql://localhost:3306/web1?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    password: root
    username: root
# 指明运行时与xxxMapper相关的xml文件路径
mybatis:
    mapper-locations: classpath*:/mybatis/*.xml